<a href="https://colab.research.google.com/github/AfrahAbdulrab/Machine-Learning/blob/main/ML_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
!pip install pandas numpy scikit-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score



In [2]:
#mount the drive
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [3]:
#loading dataset
data = pd.read_csv('/content/drive/MyDrive/ML-2/heart.csv')

In [12]:
#printing the data and description
print("Dataset Information:\n")
print(data.info())
print("\n\n\nDataset Description:\n")
print(data.describe())

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1024 non-null   float64
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1024 non-null   float64
 8   exang     1025 non-null   int64  
 9   oldpeak   1024 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(3), int64(11)
memory usage: 112.2 KB
None



Dataset Description:

               age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1024.000000  1025.00000   
mean     54.434146

In [15]:
#finding duplicates andd then dropping the duplicates
duplicates = data.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")
data = data.drop_duplicates()
print(f"Data shape after dropping duplicates: {data.shape}")

Number of duplicate rows: 0
Data shape after dropping duplicates: (304, 14)


In [18]:
#Replacing '?' with NaN
data.replace('?', np.nan, inplace=True)
print("Dataset after replacing\n")
print(data.head())

Dataset after replacing

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0     125.0   212    0        1    168.0      0      1.0      2   
1   53    1   0     140.0   203    1        0    155.0      1      3.1      0   
2   70    1   0     145.0   174    0        1    125.0      1      2.6      0   
3   61    1   0     148.0   203    0        1    161.0      0      0.0      2   
4   62    0   0     138.0   294    1        1    106.0      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  


In [19]:
#checking missing values
missing_values = data.isnull().sum()
print("Missing values in each column\n")
print(missing_values[missing_values > 0])

Missing values in each column

trestbps    1
thalach     1
oldpeak     1
dtype: int64


In [22]:
#dropping rows with null values
data_cleaned = data.dropna()
print(f"Data shape after dropping null values: {data_cleaned.shape}")


Data shape after dropping null values: (302, 14)


In [25]:
#dividing the data into train and test sets with ratio(80:20)
X = data_cleaned.drop('age', axis=1)  # Features
y = data_cleaned['age']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)




In [27]:
#Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
#applying algorithms
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

#storing results
results = {}

for name, model in models.items():
    #Fitting the model
    model.fit(X_train, y_train)

    #Predicting on test set
    y_pred = model.predict(X_test)

    #Evaluating the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = classification_report(y_test, y_pred, output_dict=True)['weighted avg']['precision']
    recall = classification_report(y_test, y_pred, output_dict=True)['weighted avg']['recall']
    f1_score = classification_report(y_test, y_pred, output_dict=True)['weighted avg']['f1-score']
    conf_matrix = confusion_matrix(y_test, y_pred)

    # Storing results
    results[name] = {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1_score,
        'Confusion Matrix': conf_matrix
    }
    #printing results
    print(f"\nResults for {name}:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1_score:.4f}")
    print("Confusion Matrix:")
    print(conf_matrix)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


Results for Logistic Regression:
Accuracy: 0.0820
Precision: 0.0549
Recall: 0.0820
F1-Score: 0.0638
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Results for Decision Tree:
Accuracy: 0.0820
Precision: 0.1585
Recall: 0.0820
F1-Score: 0.0852
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Results for KNN:
Accuracy: 0.0328
Precision: 0.0287
Recall: 0.0328
F1-Score: 0.0304
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Results for Naive Bayes:
Accuracy: 0.0492
Precision: 0.0770
Recall: 0.0492
F1-Score: 0.0497
Confusion Matrix:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [45]:
#comparing the results
print("\nComparison of Model Performance:\n")
for model_name, metrics in results.items():
    print(f"{model_name}: \nAccuracy: {metrics['Accuracy']:.4f}, "
          f"Precision: {metrics['Precision']:.4f}, "
          f"Recall: {metrics['Recall']:.4f}, "
          f"F1-Score: {metrics['F1-Score']:.4f}")


Comparison of Model Performance:

Logistic Regression: 
Accuracy: 0.0820, Precision: 0.0549, Recall: 0.0820, F1-Score: 0.0638
Decision Tree: 
Accuracy: 0.0820, Precision: 0.1585, Recall: 0.0820, F1-Score: 0.0852
KNN: 
Accuracy: 0.0328, Precision: 0.0287, Recall: 0.0328, F1-Score: 0.0304
Naive Bayes: 
Accuracy: 0.0492, Precision: 0.0770, Recall: 0.0492, F1-Score: 0.0497


In [49]:
best_model = max(results, key=lambda x: results[x]['F1-Score'])
print(f"The best performing model based on F1-Score is: {best_model}")

The best performing model based on F1-Score is: Decision Tree
